nodes: 1
tasks_per_node: 1
tag: vitl16_brainslice48_AD_bin_vjepainit_withwarmup
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/Brainslice_48_ADclassification_train_final_filtered_zoom.csv
  dataset_val: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/Brainslice_48_ADclassification_val_final_filtered_zoom.csv
  dataset_type: VideoDataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_views_per_segment: 1
  frame_step: 4
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.347
    - 0.347
    - 0.347
  - - 0.346
    - 0.346
    - 0.346
optimization:
  attend_across_segments: false
  num_epochs: 300
  resolution: 224
  batch_size: 14
  weight_decay: 0.01
  lr: 0.01
  start_lr: 0.01
  final_lr: 0.0
  warmup: 0
  use_bfloat16: true
pretrain:
  model_name: vit_large
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA/a6000_output/vit_l/vitl_vjepa_init
  checkpoint: vitlarge_vjepaInit-latest.pth.tar  # name of pretrained model file inside folder
  write_tag: vitl16_48_AD_bin_withwarmup
logging:
  project: voxel-jepa-fine-tuning # Don't change this
  run_name: vitl16_48_AD_bin_fromVJEPA_withwarmup # Please change every time before running, this is the name for wandb run file

  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vitl_vjepainit/AD_bin/vitl16_48_AD_bin_scratch.yaml --devices cuda:0
  