nodes: 8
tasks_per_node: 8
tag: vit_tiny_brainslice48_axisclassifier
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_axis_classification_slice48_mp4/Brainslice_48_Axisclassification_train.csv
  dataset_val: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_axis_classification_slice48_mp4/Brainslice_48_Axisclassification_val.csv
  dataset_type: VideoDataset
  num_classes: 3
  frames_per_clip: 16
  num_segments: 1
  num_views_per_segment: 1
  frame_step: 4
optimization:
  attend_across_segments: false
  num_epochs: 300
  resolution: 224
  batch_size: 14
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1.0
  - 1.0
  random_resize_scale:
  - 0.8
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.096
    - 0.096
    - 0.096
  - - 0.230
    - 0.230
    - 0.230
pretrain:
  model_name: vit_tiny
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA/a6000_output/pretrain_maskfix1_tiny
  checkpoint: vit_tiny_rnd.pth.tar  # name of pretrained model file inside folder
  write_tag: axisclassifier_vittiny_rnd
logging:
  project: voxel-jepa-fine-tuning # Don't change this
  run_name: axisclassifier_vittiny_rnd # Please change every time before running, this is the name for wandb run file

  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_axis_classification_slice48_mp4/vitl16_brainslice48_axisclassifier_rnd.yaml --devices cuda:0 cuda:1
  