nodes: 1
tasks_per_node: 1
tag: vit_base_mriload_k400100mri50_130epoch
eval_name: video_classification_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/eval_AD/AD_binary_train_alldata_nii_renorm.csv
  dataset_val: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/eval_AD/AD_binary_test_alldata_nii_renorm.csv
  dataset_type: mridataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_workers: 6
  num_views_per_segment: 1
  frame_step: 4
optimization:
  attend_across_segments: false
  num_epochs: 100
  resolution: 224
  batch_size: 28
  weight_decay: 0.05
  lr: 0.005
  start_lr: 0.005
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.159943
    - 0.159943
    - 0.159943
  - - 0.288280
    - 0.288280
    - 0.288280
pretrain:
  model_name: vit_base
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA/a6000_output/vit_base/K400/
  checkpoint: vitbase_mri_ctn_100epoch_from_k400_norm-latest130epochcp.pth.tar # name of pretrained model file inside folder
  write_tag: mriload_k400100mri50_130epoch

logging:
  project: voxel-jepa-ad-bin-base # Don't change this
  run_name: mriload_k400100mri50_130epoch # Please change every time before running, this is the name for wandb run file
port: 42004
  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/vitl16_brainslice48_ADbinclassifier_lr_half_fix10.yaml --devices cuda:0>/media/backup_16TB/sean/VJEPA/a6000_output/pretrain_maskfix1_tiny/video_classification_frozen/vit_tiny_brainslice48_ADbinclass/lr_half_fix10.log 2>&1
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vit_base/AD_bin/mri_load/vitbase16_brainslice48_ADbinclassifer_k400andmri_mriload.yaml --devices cuda:0 cuda:1 cuda:2
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vit_base/AD_bin/mri_load/vitbase16_brainslice48_ADbinclassifer_k400andmri_mriload_130epoch.yaml --devices cuda:2 --validation True  