nodes: 1
tasks_per_node: 1
tag: vit_base_k400
eval_name: video_regression_frozen
resume_checkpoint: false
data:
  dataset_train: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/age_train_data.csv
  dataset_val: /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000_csv/age_test_data.csv
  dataset_type: VideoDataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 1
  num_workers: 6
  num_views_per_segment: 1
  frame_step: 4
optimization:
  attend_across_segments: false
  num_epochs: 300
  resolution: 224
  batch_size: 14
  weight_decay: 0.005
  lr: 0.0005
  start_lr: 0.0005
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
  normalize:
  - - 0.347
    - 0.347
    - 0.347
  - - 0.346
    - 0.346
    - 0.346
pretrain:
  model_name: vit_base
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /media/backup_16TB/sean/VJEPA/a6000_output/vit_base/K400/
  checkpoint: K400_base_200epoch-latest.pth.tar # name of pretrained model file inside folder
  write_tag: K400_only_200epoch

logging:
  project: voxel-jepa-age-regress-base # Don't change this
  write_tag: K400_only_200epoch # Please change every time before running, this is the name for wandb run file
port: 42008
  ##todo run tomorrow 9th april.
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/pretrain_maskfix_tiny/tiny_AD_binclass_slice48_mp4/vitl16_brainslice48_ADbinclassifier_lr_half_fix10.yaml --devices cuda:0>/media/backup_16TB/sean/VJEPA/a6000_output/pretrain_maskfix1_tiny/video_classification_frozen/vit_tiny_brainslice48_ADbinclass/lr_half_fix10.log 2>&1
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vit_base/age_regress/vitbase16_brainslice48_ageregress_fix18_200epoch.yaml --devices cuda:2
  #python -m evals.main --fname /media/backup_16TB/sean/VJEPA/jepa/configs/evals_a6000/vit_base/age_regress/vitbase16_brainslice48_ageregress_k400.yaml --devices cuda:2 --plotter csv --validation True